[tool.black]
max-line-length = 100
target_version = ['py38']
include = '\.pyi?$'
exclude = '''
(
  /(
    | \.git
    | \.virtualenv
    | __pycache__
    | test_content_version
  )/
)
'''

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-l"

[tool.setuptools.packages.find]
where = ["."]  # list of folders that contain the packages (["."] by default)
include = ["st2common"]  # package names should match these glob patterns (["*"] by default)
exclude = []  # exclude packages matching these glob patterns (empty by default)
namespaces = false  # to disable scanning PEP 420 namespaces (true by default)
